{ lib }:
let
  inherit (builtins) attrNames;
  inherit (lib) concatStringsSep optionalString;
  s = import ../lib/scheme.nix { inherit lib; };

  # core modules provided by the steel-enabled Helix fork
  coreRequires = [
    "helix/configuration.scm"
    "helix/keymaps.scm"
    "helix/editor.scm"
    "helix/misc.scm"
    "helix/commands.scm"
    "helix/components.scm"
  ];
in
rec {
  renderLsp = l: concatStringsSep "\n" [
    (s.call "define-lsp" [ (s.str l.serverName) (s.call "command" [ (s.str l.serverName) ]) (s.call "args" [ s.empty ]) ])
    (s.call "define-language" [ (s.str l.language) (s.call "language-servers" [ (s.quoteList [ (s.str l.serverName) ]) ]) ])
  ];

  render =
    nhxCfg:
    let
      steelCfg = nhxCfg.steel;
    in
    concatStringsSep "\n\n" (
      lib.filter (line: line != "") [
        ";; generated by nhx (modules/init-scm.nix). Do not edit by hand."
        (concatStringsSep "\n" (map (r: s.call "require" [ (s.str r) ]) coreRequires))
        (optionalString steelCfg.lsp.enable (renderLsp steelCfg.lsp))
      ]
    );
}
