{ lib }:
let
  inherit (builtins) attrNames;
  inherit (lib) concatStringsSep optionalString;
  s = import ../lib/scheme.nix { inherit lib; };

  # core modules provided by the steel-enabled Helix fork; user definitions of
  # coreRequires are added on top of these
  coreDefaults = [
    "helix/configuration.scm"
    "helix/keymaps.scm"
    "helix/editor.scm"
    "helix/misc.scm"
    "helix/commands.scm"
    "helix/components.scm"
  ];
in
rec {
  # extra require entries are local scheme files (paths relative to the config
  # file), installed next to init.scm and required by their basename
  fileBaseName = e: lib.last (lib.splitString "/" (toString e));

  extraRequireLine = e: s.call "require" [ (s.str (fileBaseName e)) ];

  # keymap hashes for buffer and extension keymaps
  renderKeyEntry =
    key: value:
    if lib.isString value then
      s.hashEntry (s.str key) (s.str value)
    else if lib.isList value then
      s.hashEntry (s.str key) (s.list (map s.str value))
    else if lib.isAttrs value then
      s.hashEntry (s.str key) (renderKeyHash value)
    else
      throw "nhx: keymap value for ${key} must be a string, list or attrset";

  renderKeyHash = attrs: s.hash (map (key: renderKeyEntry key attrs.${key}) (attrNames attrs));

  renderOilKeymaps = keymaps:
    concatStringsSep "\n" [
      (s.call "define" [ "oil-keymaps" (renderKeyHash keymaps) ])
      (s.call "define" [ "oil-keybindings" (s.call "deep-copy-global-keybindings" [ ]) ])
      (s.call "merge-keybindings" [ "oil-keybindings" "oil-keymaps" ])
      (s.call "set-global-buffer-or-extension-keymap" [
        (s.hash [ (s.hashEntry "OIL-BUFFER-NAME" "oil-keybindings") ])
      ])
    ];

  renderLsp = l: concatStringsSep "\n" [
    (s.call "define-lsp" [ (s.str l.serverName) (s.call "command" [ (s.str l.serverName) ]) (s.call "args" [ s.empty ]) ])
    (s.call "define-language" [ (s.str l.language) (s.call "language-servers" [ (s.quoteList [ (s.str l.serverName) ]) ]) ])
  ];

  render =
    nhxCfg:
    let
      steelCfg = nhxCfg.steel;
      names = attrNames nhxCfg.plugins;

      reqOf =
        name: p:
        optionalString p.enable (
          s.call "require" [ (s.str (if p.requirePath != null then p.requirePath else "${name}/${name}.scm")) ]
        );

      requiresBlock = concatStringsSep "\n" (
        lib.filter (l: l != "") (
          (map (r: s.call "require" [ (s.str r) ]) (lib.unique (coreDefaults ++ nhxCfg.coreRequires)))
          ++ (map (name: reqOf name nhxCfg.plugins.${name}) names)
          ++ (map extraRequireLine nhxCfg.extraRequires)
        )
      );

      pluginSections = concatStringsSep "\n\n" (
        lib.filter (l: l != "") (
          map (
            name:
            let
              p = nhxCfg.plugins.${name};
              extra = optionalString (p.enable && p.extra != "") p.extra;
            in
            concatStringsSep "\n" (lib.filter (line: line != "") [ p.rendered extra ])
          ) names
        )
      );
    in
    concatStringsSep "\n\n" (
      lib.filter (line: line != "") [
        ";; generated by nhx (modules/init-scm.nix). Do not edit by hand."
        (optionalString (requiresBlock != "") requiresBlock)
        (optionalString steelCfg.lsp.enable (renderLsp steelCfg.lsp))
        (optionalString (pluginSections != "") pluginSections)
        (optionalString (steelCfg.extra != "") steelCfg.extra)
      ]
    );
}
